
seed:
  image: "docker-compose-akka-cluster:0.1-SNAPSHOT"
  hostname: "akkaseed"
  command: "-Dakka.remote.netty.tcp.hostname=akkaseed"

node:
  image: "docker-compose-akka-cluster:0.1-SNAPSHOT"
  links: ["seed:akkaseed"]
